// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGScAyIclmct49g3FFZfhWHbYuR315sC0',
    appId: '1:677259627885:web:9c5aa8a2d0bdb20d721e64',
    messagingSenderId: '677259627885',
    projectId: 'notes-f6fe1',
    authDomain: 'notes-f6fe1.firebaseapp.com',
    storageBucket: 'notes-f6fe1.appspot.com',
    measurementId: 'G-0Y9MKJNXJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLyi-awOBUFb2JOt7m3f5HeoxH-2OV400',
    appId: '1:677259627885:android:c28a389916529cbe721e64',
    messagingSenderId: '677259627885',
    projectId: 'notes-f6fe1',
    storageBucket: 'notes-f6fe1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM1r6R4vgTFgjWefHoRvYRArBP6vNUJ8k',
    appId: '1:677259627885:ios:c8460ba4e36f274e721e64',
    messagingSenderId: '677259627885',
    projectId: 'notes-f6fe1',
    storageBucket: 'notes-f6fe1.appspot.com',
    iosBundleId: 'com.example.m4htnsa.m4Htnsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM1r6R4vgTFgjWefHoRvYRArBP6vNUJ8k',
    appId: '1:677259627885:ios:3a1dfc42b6888ac4721e64',
    messagingSenderId: '677259627885',
    projectId: 'notes-f6fe1',
    storageBucket: 'notes-f6fe1.appspot.com',
    iosBundleId: 'com.example.m4htnsa.m4Htnsa.RunnerTests',
  );
}
